Gama.TesteASPNETMVC.WEB/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gama.TesteASPNETMVC.WEB.Models
{
    public class Pessoa
    {
        //Referencia se é requirido ou não e o erro que será exibido
        [Required (ErrorMessage ="O nome é obrigatório")]
        //Mostra o nome que será exibido na label
        [DisplayName("Nome:")]
        //Referencia o mínimo de caracteres aceito
        [MinLength(5,ErrorMessage ="Nome com no mínimo 5 caracteres")]
        //Referencia o máximo de caracteres aceito
        [MaxLength (50, ErrorMessage ="Nome com no máximo 50 caracteres")]
        public string Nome { get; set; }

        //Mostra o nome que será exibido na label
        [DisplayName("Idade:")]
        public int idade { get; set; }


        //Referencia se é requirido ou não e o erro que será exibido
        [Required(ErrorMessage = "O endereço é obrigatório")]
        //Mostra o nome que será exibido na label
        [DisplayName("Endereço:")]
        //Referencia o máximo de caracteres aceito
        [MaxLength(100, ErrorMessage = "Endereco com no máximo 100 caracteres")]
        public string Endereco { get; set; }

        //Referencia se é requirido ou não e o erro que será exibido
        [Required(ErrorMessage = "O email é obrigatório")]
        //Mostra o nome que será exibido na label
        [DisplayName("Email:")]
        //Referencia o máximo de caracteres aceito
        [MaxLength(20, ErrorMessage = "Email com no máximo 20 caracteres")]
        //Valida se o tipo de campo digitado é mesmo email
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public bool Ativo { get; set; }
    }
}

Gama.TesteASPNETMVC.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gama.TesteASPNETMVC.WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Gama.TesteASPNETMVC.WEB/Controllers/TesteController.cs
using Gama.TesteASPNETMVC.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gama.TesteASPNETMVC.WEB.Controllers
{
    public class TesteController : Controller
    {
        // GET: Teste
        public ActionResult Index()
        {
            return View();
        }
        //Valida o token transmitido
        [ValidateAntiForgeryToken]
        //Referencia o tipo de retorno (Get ou Post)
        [HttpPost]
        //ActionResult retorna uma view
        
            /*Bind permite o Include e exclude. 
             * Exclude para que não seja possível o ataque de parâmetros mesmo que forçados por hackers*/
        public ActionResult Index([Bind(Exclude ="Ativo")]Pessoa pessoa) {
            /*ModelState é utilizado para caso não haja um javascript e mesmo assim seja validado os campos*/
            if (ModelState.IsValid)
            {
                
                pessoa.Ativo = true;
                //Retornando a View Saudação com o objeto pessoa
                return View("Saudacao", pessoa);

            }
            else {
                //Retornando a View Index com o objeto pessoa e os erros
                return View(pessoa);
            }
        }

        
    }
}

Gama.TesteASPNETMVC.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Gama.TesteASPNETMVC.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Gama.TesteASPNETMVC.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Gama.TesteASPNETMVC.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <!--Scripts referenciados do App_Start/BundleConfig.cs -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

Gama.TesteASPNETMVC.WEB/Views/Teste/Index.cshtml
<!--Referencia o modelo a ser recebido -->
@model Gama.TesteASPNETMVC.WEB.Models.Pessoa
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<br/>
<br />
<!--Referencia o início do form na view Index, Controller Teste e com method post-->
@using (Html.BeginForm("Index","Teste",FormMethod.Post)) { 
<p>Digite seu nome:</p>
    <!--ValidationSummary: Exibe apenas os erros identificados com false, com true apresenta qualquer erro-->
    @Html.ValidationSummary(false)
    <!--Cria Token de sessão-->
    @Html.AntiForgeryToken()

    <!--Cria a label do objeto-->
    @Html.LabelFor(p => p.Nome)
    <!--Cria o campo texto já no formato do objeto, new referencia o id e/ou a class do css-->
    @Html.EditorFor(p=>p.Nome, new { id = "txtNome", @class = "minhaClasseCss" })
    <!--Exibe se houver erros a mensagem no HTML-->
    @Html.ValidationMessageFor(p=> p.Nome)
    <!--Cria a label do objeto-->
    @Html.LabelFor(p => p.idade)
    <!--Cria o campo texto já no formato do objeto, new referencia o id e/ou a class do css-->
    @Html.EditorFor(p => p.idade, new { id = "txtidade", @class = "minhaClasseCss" })
    <!--Cria a label do objeto-->
    @Html.LabelFor(p => p.Endereco)
    <!--Cria o campo texto já no formato do objeto, new referencia o id e/ou a class do css-->
    @Html.EditorFor(p => p.Endereco, new { id = "txtEndereco", @class = "minhaClasseCss" })
    <!--Exibe se houver erros a mensagem no HTML-->
    @Html.ValidationMessageFor(p => p.Endereco)
    <!--Cria a label do objeto-->
    @Html.LabelFor(p => p.Email)
    <!--Cria o campo texto já no formato do objeto, new referencia o id e/ou a class do css-->
    @Html.EditorFor(p => p.Email, new { id = "txtEmail", @class = "minhaClasseCss" })
    <!--Exibe se houver erros a mensagem no HTML-->
    @Html.ValidationMessageFor(p => p.Email)

<input type="submit" value="Enviar" />
}

Gama.TesteASPNETMVC.WEB/Views/Teste/Saudacao.cshtml
<!--Chama a pasta models-->
@using Gama.TesteASPNETMVC.WEB.Models
<!--Chama o modelo pessoa-->
@model Pessoa
@{
    ViewBag.Title = "Saudacao";
}

<h2>Saudacao</h2>
<p>Olá, seja bem vindo @Model.Nome</p> 
<!--Chama as labels do objeto e o editor do formato do objeto-->
@Html.LabelFor(p=>p.idade)@Html.EditorFor(p=>p.idade)
@Html.LabelFor(p=>p.Endereco)@Html.EditorFor(p => p.Endereco)
@Html.LabelFor(p => p.Email)@Html.EditorFor(p => p.Email)